name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - mlflow==2.8.1
  - pip:
      - wandb==0.16.0
      - databricks_cli==0.8.7
